httputil/README.md, httputil/json.go, httputil/json_test.go, test
* Allows other projects to easily add a health-check endpoint with
custom checks.
* Health code is mostly cribbed from coreos-inc/auth/pkg health; once
this has landed we can remove that and have it depend on this instead
* Also started an HTTPUtil which right now just has a method for writing
JSON responses.
=> httputil: Add a package for common http code.

health/README.md, health/health.go, health/health_test.go, test
* Allows other projects to easily add a health-check endpoint with
custom checks.
* Health code is mostly cribbed from coreos-inc/auth/pkg health; once
this has landed we can remove that and have it depend on this instead.
=> health: add health-checking package.

health/health.go, health/health_test.go
Now the object itself is a handler, and we don't need the extra method.
=> health: Replace MakeHealthHanlderFunc with ServeHTTP

capnslog/log_hijack.go, capnslog/logmap.go, capnslog/pkg_logger.go
Commit cb18954f removed the LogEntry interface and most references to
its one implementation, BaseLogEntry. Finish the job.
=> capnslog: remove useless BaseLogEntry type

capnslog/pkg_logger.go
Useful for creating utility functions like:
```go
func LogLines(l capnslog.LogLevel, r io.Reader) {
scanner := bufio.NewScanner(r)
for scanner.Scan() {
logger.Log(l, scanner.Text())
}
if err := scanner.Err(); err != nil {
logger.Errorf("Reading %s failed: %v", r, err)
}
}
```
=> capnslog: add methods for logging at arbitrary levels

capnslog/example/hello_dolly.go, capnslog/logmap.go
LogLevel now fulfills the flag.Value interface and example updated.
./example -log-level=NOTICE
=> capnslog: support setting LogLevel via command line flags

httputil/cookie.go, httputil/cookie_test.go
It is common to want to delete a set of named cookies, for example when a user logs out of a website.
=> httputil: add helper func for cookie deletion

capnslog/example/hello_dolly.go, capnslog/formatters.go, capnslog/init.go, capnslog/journald_formatter.go, capnslog/log_hijack.go, capnslog/pkg_logger.go
Chasing #26. 
This is a little bold, but somebody's got to take a position and go for consensus. Here's some thoughts on sane defaults and a real CoreOS formatter.
The notion is as follows: we have a common log format, for which I'm proposing this:
```
INFO | 2015-06-11 15:17:16.3707 | dolly: Hello Dolly
WARNING | 2015-06-11 15:17:16.3707 | dolly: Well hello, Dolly
ERROR | 2015-06-11 15:17:16.3707 | main: It's so nice to have you back where you belong
INFO | 2015-06-11 15:17:16.3708 | You're still glowin', you're still crowin', you're still lookin' strong
CRITICAL | 2015-06-11 15:17:16.3708 | main: Dolly'll never go away again
```
But wait, there's more! A built-in debug flag to the CoreOS formatter yields the following:
```
INFO | 2015-06-11 15:21:46.0527 [proc.go:63] | dolly: Hello …
```
=> capnslog: Set some defaults, propose a CoreOS formatter

capnslog/journald_formatter.go
Fixes #40. I think it's reasonable to just set this by default rather than
needing to expose it to users.
References:
http://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#SYSLOG_FACILITY=
http://linux.die.net/man/3/program_invocation_short_name
=> capnslog: set SYSLOG_IDENTIFIER for journal

README.md
This adds a little badge that links to `coreos/pkg` documentation at godoc.org.
Thanks,
=> README: add godoc badge and link

flagutil/env_file.go, flagutil/file_env_test.go
* Allow binaries to read from simple env var files so wrapper
script entrypoints aren't needed to source Kubernetes secret files
I've been wanting to improve upon using wrapper script entrypoints to source Kubernetes secrets files (deployment detail) in some projects, until Kubernetes environment variable secrets are supported. With `SetFlagsFromEnvFile` the binary is endowed with the ability to source variables from a file, typically set via `ENV_FILE` or `SECRETS_FILE`. Here's the change if others are also interested in this.
=> flagutil: Add SetFlagsFromEnvFile

capnslog/pkg_logger.go
```
WARNING: DATA RACE
Read by goroutine 46:
github.com/coreos/pkg/capnslog.(*PackageLogger).internalLog()
/home/mischief/code/go/src/github.com/coreos/pkg/capnslog/pkg_logger.go:30 +0x41
github.com/coreos/pkg/capnslog.(*PackageLogger).Info()
/home/mischief/code/go/src/github.com/coreos/pkg/capnslog/pkg_logger.go:131 +0x5a
...
Previous write by goroutine 44:
github.com/coreos/pkg/capnslog.RepoLogger.setRepoLogLevelInternal()
/home/mischief/code/go/src/github.com/coreos/pkg/capnslog/logmap.go:169 +0xba
github.com/coreos/pkg/capnslog.SetGlobalLogLevel()
/home/mischief/code/go/src/github.com/coreos/pkg/capnslog/logmap.go:136 +0x153
...
```
=> capnslog: fix small race on PackageLogger.level

capnslog/pkg_logger.go
Eliminate some unnecessary repetition
=> capnslog: use common function for formatted logging

capnslog/pkg_logger.go
Because Trace and Debug may be called in critical paths, avoiding the Sprintf when not in use is a performance gain.
=> capnslog: pessimistically abort before sprintf

capnslog/formatters.go
This resolves: https://github.com/coreos/etcd/issues/4115
=> Offer the ability to pass through standard capnslog when embedding.

README.md
Switched to travis instead for now.
=> README: remove Semaphore badge

progressutil/iocopy.go, progressutil/progressbar.go
progressutil is a utility for displaying progress bars to a user. It can
support multiple progress bars at once, and will detect when not drawing
to a terminal and change its behavior appropriately.
Currently needed for concurrent layer pulls in docker2aci.
=> progressutil: add initial implementation

capnslog/formatters.go
This is useful for turning off logs on a project that uses capnslog that
you're embedding.
=> capnslog: Add NilFormatter for silencing unwanted log messages

progressutil/iocopy.go, progressutil/progressbar.go
docker2aci has some race conditions, and go's race detector found some
race-y accesses in progressutil, so this commit wraps some variables
shared between goroutines in mutexes.
=> progressutil: added mutexes to make go's race detector happy

progressutil/iocopy.go, progressutil/progressbar.go
Rather than maintaining a list of results and individual synchronised
booleans signifying goroutine completion, just use a single channel to
propagate the result of each copyReader
---
This is a rebased version of #62 and #63, and supercedes both.
=> progressutil: refactor to use channels

k8s-tlsutil/k8s-tlsutil.go
pulls in some handy code from bootkube
https://github.com/coreos/bootkube/blob/master/pkg/tlsutil/tlsutil.go
Only change is to allow override of valid duration (still uses same defaults though).
=> k8s-tlsutil: add k8s-tlsutil pkg

capnslog/pkg_logger.go
I want to plug in capnslog for etcd clientv3 logger
to make it consistent with etcd package loggers.
And grpclog.Logger interface needs Fatalln method.
=> capnslog: add Fatalln method

netutil/proxy.go
This commit decouples netutil from capnslog, making it easier to
later deprecate it and to fix dependency loops between coreos/pkg
and coreos/go-systemd.
References:
* https://github.com/coreos/pkg/issues/73#issuecomment-228034278
* https://github.com/coreos/pkg/issues/57
=> netutil: remove capnslog dependency

capnslog/pkg_logger.go
This commit adds a Panicln method to the PackageLogger to make it
implement all of the golang/log logging methods and thus making it
implement with the logrus.StdLogger interface. I want this so that Dex
can accept loggers from packages that use capnslog, notably bridge. This
is the only missing method to fulfil the interface.
=> capnslog: implement logrus.StdLogger
